[package]
name = "memoffset"
version = "0.1.0"
authors = ["Gilad Naaman <gilad.naaman@gmail.com>"]
description="offset_of functionality for Rust structs."
license="MIT"
readme="README.md"

[dependencies]

[features]
default = ["std"]
std = []
